version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.2.0-beta.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: vilicando_secure
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: guest
      HASURA_GRAPHQL_JWT_SECRET: >-
        {"type": "RS512", "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqBUrEKZfK5SQDH+bSLYL\nshz2hz5LkxXPzAe4nyu2nBrT22jLSniPaVzbCVoGJ3rbNzp8hV1DAymRp8xRDOZ8\nWCMM8lFezY4+RvqrXZ2q9LEV+gY8+c1iWAzlgUyQSwXI/rAaRY2I8AMSx4oJ79U6\nOkPiDV+OndgH1Q4+kGdLxUDCy1gkEYcfzWmVOsIdPAkzMUkMUw2V9i/tqK+JDwSo\n2LAuuxwaS/fgLQdbjN3gP4OMt2M949KxCCWXwwNke2Qkzv//LJKwQO+wXKrmKTbE\nCMWROUB3D/6VKrNM4IKAV71kXPt1B69CrzASVngIzNdVbUz0286iKGoY1h1N2qiB\nuwIDAQAB\n-----END PUBLIC KEY-----\n"}
volumes:
  db_data:
